### PR TITLE
New & changed scan - null values fix

### LINKED ISSUE #1493: Play stats not updating after adding MB_TrackID on New & Change scan (introduced in 9.1)
**Describe the bug**
Following up on my post here as I have now reproduced this consistently: https://forums.lyrion.org/forum/user-forums/logitech-media-server/1807525-9-1-0-x-album-rescan?p=1807585#post1807585

After a New & Change Scan (or Album Rescan) where an MB_TrackID was added to an existing tracks that were not previously tagged with MBIDs, play stats for those tracks are not updating until a Full Wipe & Rescan is completed.

No related error messages in either scanner.log or server.log

This appears like it might be a regression in 9.1.  I repeated the steps on 9.0.4 and playing stats were successfully updating.

Note of possible interest: 
I am able to update ratings on the tracks.  I have the Ratings Light plugin installed.

**To Reproduce**
1. Add MB_TrackID to an existing album in your LMS library that did not contain any before
2. Run New & Change Scan
3. Play tracks and observe that the play stats are not updating

**Expected behavior**
Play count and last played date updating when tracks are played.  This issue has become more apparent since adding the Recently Played Home Extra to my Material home screen

**System Information (please complete the following information):**
 - Ubuntu 20.04  x86_64
 - Material on Chrome (Mac)
 - Issue on: Version: 9.1.0 - 1768842567 @ Tue Jan 20 03:17:39 UTC 2026
 - Working as expected: Version: 9.0.4 - 1768542180 @ Sat Jan 17 03:12:35 UTC 2026
 - SB Touch

@darrell-k  - could this be related to any of the changed you made in 9.1?

### PR DESCRIPTION
**Pull request by darrell-k**
Issue #1493 

Also fix inconsistent behaviour when setting previously populated columns to null in a new & changed scan - depending on the user's tagging software, we might not get tags set to null at all.

Should we be extending the new list of nullable columns `$nullableColumns`?

This could fix other reported inconsistencies in the N&C scan, so I think it's worth backporting to 9.0.

I also found we need to issue an `update()` to the `TrackPersistent` object, otherwise the changed columns remain "dirty" and never get committed to the database. I don't know if this has never worked, or if there have been recent(ish) changes to the underlying libraries.

### CODE REVIEW

**Comment by michaelherger** [comment]
I'm sorry, I'm out for a week. This might have to wait a few days...

**Comment by darrell-k** [comment]
> I'm sorry, I'm out for a week. This might have to wait a few days...

No problem.

**Comment by darrell-k** [comment]
@mikeysas in the meantime you could replace your Slim/Schema.pm (in 9.1) with this https://raw.githubusercontent.com/LMS-Community/slimserver/326f506cf8bf13adc76d67c0220d38067db2f813/Slim/Schema.pm and see if it helps.

**Comment by mikeysas** [comment]
> @mikeysas in the meantime you could replace your Slim/Schema.pm (in 9.1) with this https://raw.githubusercontent.com/LMS-Community/slimserver/326f506cf8bf13adc76d67c0220d38067db2f813/Slim/Schema.pm and see if it helps.

I just did a quick test using the Album Rescan and MBID's were updated in `tracks_persistent` and play stats updated.  I will do some more testing as I update more tags and let you know if I see an issue, but looks good to me. Thx!

**Comment by audiomuze** [comment]
@darrell-k, is this intended to resolve the issue of inability to land 1:1 contributor to mbid mappings (if a user's tagger is able to place delimiters or write blank tags)?  I cannot help but feel that without that being resolved using mbid's in Lyrion is pointless because you'll inevitably encounter situations where a mbid is associated with the wrong contributor.

**Comment by darrell-k** [comment]
> @darrell-k, is this intended to resolve the issue of inability to land 1:1 contributor to mbid mappings (if a user's tagger is able to place delimiters or write blank tags)? I cannot help but feel that without that being resolved using mbid's in Lyrion is pointless because you'll inevitably encounter situations where a mbid is associated with the wrong contributor.

No, it is a different issue. This PR ensures that the tracks_persistent table stays in sync with the main tracks table, and also that when a user removes a tag and does a new/changed scan the previously populated column is the tracks table is nulled.

File: Slim/Schema.pm [hunk 1]
```diff
@@ -2024,13 +2035,14 @@ sub updateOrCreateBase {
...
 			# Metadata is only included if it contains a non zero value
-			if ( main::STATISTICS && $val && blessed($trackPersistent) && exists $trackPersistentAttrs->{$key} ) {
+			if ( main::STATISTICS && ($val || $nullableColumns->{$key}) && blessed($trackPersistent) && exists $trackPersistentAttrs->{$key} ) {
 
 				main::INFOLOG && $log->is_info && $log->info("Updating persistent $url : $key to $val");
 
 				$trackPersistent->set_column( $key => $val );
 			}
 		}
+		$trackPersistent->update() if blessed($trackPersistent);
```
Comment (michaelherger) [inline Slim/Schema.pm:2045]: We didn't call `update()` before. Would that mean that we never even wrote back those updated values?

Comment (darrell-k) [reply Slim/Schema.pm:2045]: As I mentioned above, presumably, unless behaviour has changed in the underlying libraries.

I think probably it's never worked.

**Review by michaelherger — APPROVED** [review]
Thanks - looking good to me.

**Comment by darrell-k** [comment]
Should we be adding any other columns to `$nullableColumns`?
